baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'


[params]
  title = 'CVLM'
  metaDescription = "Cercle de la Voile de Lyon - Meyzieu"


# Languages
[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 1
mark = "FR"

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
mark = "EN"

[menu]
  [[menu.main]]
    identifier = "RecentPosts"
    name = "Recent Posts"
    url = "/recent-posts/"
    weight = 10

  [[menu.main]]
    identifier = "ArchivePosts"
    name = "Archive Posts"
    url = "/archive-posts/"
    weight = 20


[taxonomies]
  category= "theme"
  scene = "scenes"
