baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'


[params]
  title = 'CVLM'
  metaDescription = "Cercle de la Voile de Lyon - Meyzieu"


# Languages
[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 1
mark = "FR"

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
mark = "EN"




[taxonomies]
  category= "theme"
  scene = "scenes"
