# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: true
locale: 'fr'

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [ fr, en ]
  default_locale: fr


# collections configuration
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/fr/recent-posts" # The path to the folder where the documents are stored
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Titre",
          name: "title", 
          widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { label: "Image", 
          name: "image", 
          widget: "image", 
          required: false }
      - { label: "Corps", name: "body", widget: "markdown" }
      - { label: "Images", name: "images", widget: "list", fields: [
          { label: "Image", name: "image", widget: "image" }
        ]}
